server:
  port: 9033
  
spring:
  datasource:
    url: <postgres url>
    password: <password>
    username: <username>
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
